### ISSUE TITLE
Log remains empty

### ISSUE THREAD

**Issue by SoftCreatR** [vbattula/salesforce-logger#5]
I've executed a hand full of logging operations (via anonymous apex, and also directly within an apex class) but the log remains empty:

![image](https://user-images.githubusercontent.com/81188/142609746-f73519cc-e961-45b8-83d2-54280a8ef835.png)

Did I miss something?

**Comment by vbattula** [comment]
Metadata entry may be missing if you have installed it couple of days earlier. Please reinstall, it should get default custom metadata entry with developer name "System".

**Comment by SoftCreatR** [comment]
Thank you for your answer. I've just deployed the logger an hour ago, so Metadata exists:

![image](https://user-images.githubusercontent.com/81188/142610969-2a664f1c-8d78-4715-8c20-34666fac106d.png)

**Comment by vbattula** [comment]
Thanks for testing it. I just did a fresh install in a new org and it seem to produce logs. Would you mind sharing debug log for anonymous execution of couple of log statements?

**Comment by SoftCreatR** [comment]
```
Executing:
=====================================
String message = 'Test';

Logger.error(message);
Logger.warn(message);
Logger.info(message);
Logger.debug(message);
Logger.fine(message);
Logger.finer(message);
Logger.finest(message);
=====================================
Success.

13:34:19.62 (73902727)|USER_DEBUG|[44]|ERROR|Test
13:34:19.62 (76588066)|USER_DEBUG|[44]|WARN|Test
13:34:19.62 (77639981)|USER_DEBUG|[44]|INFO|Test
13:34:19.62 (78610099)|USER_DEBUG|[44]|DEBUG|Test
```

I've tried to manually insert a log entry to see if I forgot permissions or something:

```
LogEntry__c le = new LogEntry__c();
le.Class__c = 'Account';
le.Level__c = 'INFO';
le.Line__c = 123;
le.Message__c = 'Foo';

insert le;
```

That worked:

```
SELECT FIELDS(ALL) FROM LogEntry__c LIMIT 200
```

=>

<html>
<body>


Id | OwnerId | IsDeleted | Name | CurrencyIsoCode | CreatedDate | CreatedById | LastModifiedDate | LastModifiedById | SystemModstamp | LastViewedDate | LastReferencedDate | Class__c | CreatedTime__c | Level__c | Line__c | Message__c | Method__c | Quiddity__c | RequestId__c | Source__c | User__c
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
a4m7Z000001Z5ozQAC | 0051i000002KgnyAAC | false | LOG-00000 | EUR | 2021-11-19T12:33:10.000Z | 0051i000002KgnyAAC | 2021-11-19T12:33:10.000Z | 0051i000002KgnyAAC | 2021-11-19T12:33:10.000Z |   |   | Account |   | INFO | 123.0 | Foo |   |   |   |   |  


</body>
</html>

**Comment by vbattula** [comment]
I see, you always need to flush to save the log entries. 

Please add  Logger.flush(); at the end. 

I thought adding immediate flush() capability for every log entry. But making a DML for every log statement is very expensive. Hence all log entries are kept in memory and requires explicit flush.

**Comment by SoftCreatR** [comment]
Ah, nice:

<html>
<body>


Id | OwnerId | IsDeleted | Name | CurrencyIsoCode | CreatedDate | CreatedById | LastModifiedDate | LastModifiedById | SystemModstamp | LastViewedDate | LastReferencedDate | Class__c | CreatedTime__c | Level__c | Line__c | Message__c | Method__c | Quiddity__c | RequestId__c | Source__c | User__c
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
a4m7Z000001Z5p4QAC | 0051i000002KgnyAAC | false | LOG-00001 | EUR | 2021-11-19T12:44:13.000Z | 0051i000002KgnyAAC | 2021-11-19T12:44:13.000Z | 0051i000002KgnyAAC | 2021-11-19T12:44:13.000Z |   |   |   | 2021-11-19T12:44:13.000Z | ERROR |   | Test |   | ANONYMOUS | 4fYnB2zN13M5cdG-mMiCZ- | Apex:AnonymousBlock.anonymous#3 | 0051i000002KgnyAAC
a4m7Z000001Z5p5QAC | 0051i000002KgnyAAC | false | LOG-00002 | EUR | 2021-11-19T12:44:13.000Z | 0051i000002KgnyAAC | 2021-11-19T12:44:13.000Z | 0051i000002KgnyAAC | 2021-11-19T12:44:13.000Z |   |   |   | 2021-11-19T12:44:13.000Z | WARN |   | Test |   | ANONYMOUS | 4fYnB2zN13M5cdG-mMiCZ- | Apex:AnonymousBlock.anonymous#4 | 0051i000002KgnyAAC
a4m7Z000001Z5p6QAC | 0051i000002KgnyAAC | false | LOG-00003 | EUR | 2021-11-19T12:44:13.000Z | 0051i000002KgnyAAC | 2021-11-19T12:44:13.000Z | 0051i000002KgnyAAC | 2021-11-19T12:44:13.000Z |   |   |   | 2021-11-19T12:44:13.000Z | INFO |   | Test |   | ANONYMOUS | 4fYnB2zN13M5cdG-mMiCZ- | Apex:AnonymousBlock.anonymous#5 | 0051i000002KgnyAAC


</body>
</html>

Thank you very much, now it works like a charm.

**Comment by SoftCreatR** [comment]
So far, so good. Log Entries are created fine, even within real world examples.

The only thing I don't understand is the main tab "Log Monitor", that shows an empty table:

![image](https://user-images.githubusercontent.com/81188/142626538-be57a777-7ab9-43f4-b9fe-16f9ddedd5bf.png)

What's the difference between "Log Monitor" and "Log Entries" and why is "Log Monitor" still empty?

**Comment by vbattula** [comment]
Log Monitor is LWC listens to platform event (Log__c), filters the events that belong to logged in user and creates a tree with all log entries that belong to same "request Id". Important thing is it should be active and actively listening while log entries are made. Change of tab resets the data. You can also add this component to utility bar, which may be better for monitoring. Log entries is standard list view on the LogEntry object.

**Comment by SoftCreatR** [comment]
Ah, I see. Works too without problems so far. Thank you very much.
